spring:
  jpa:
    generate-ddl: 'true'
    defer-datasource-initialization: 'true'
    show-sql: 'true'
  application:
    name: users-service
  datasource:
    password: password
    username: jokyaku
    url: jdbc:postgresql://localhost:5432/jokyaku-users
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://localhost:9102/eureka/
    fetch-registry: 'true'
  instance:
    prefer-ip-address: 'true'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
server:
  port: '9098'
